

import 'package:oraculum/models/tarot_model.dart';

class LoadCards {

  static List<TarotCard> getCards() {
    return [
      TarotCard(
        id: '0',
        name: 'O Louco',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_fool.png?alt=media&token=6e81fb46-2471-42c3-81e2-e9c7f9f6f981',
        description: 'O início de uma jornada espiritual ou pessoal.',
        uprightMeaning: 'Novos começos, espontaneidade, liberdade, fé.',
        reversedMeaning: 'Imprudência, indecisão, falta de preparo.',
        suit: 'Arcanos Maiores',
        number: 0,
        keywords: ['início', 'liberdade', 'aventura', 'fé'],
      ),
      TarotCard(
        id: '1',
        name: 'O Mago',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_magician.png?alt=media&token=c1dce60c-b915-452c-bb1c-b2a064fc7029',
        description: 'Poder de manifestar a realidade com sabedoria.',
        uprightMeaning: 'Habilidade, iniciativa, foco, manifestação.',
        reversedMeaning: 'Manipulação, insegurança, truques.',
        suit: 'Arcanos Maiores',
        number: 1,
        keywords: ['ação', 'magia', 'potencial', 'realização'],
      ),
      TarotCard(
        id: '2',
        name: 'A Sacerdotisa',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_priestess.png?alt=media&token=ee3877f3-e822-45e9-b39a-6a6458ef80f3',
        description: 'Intuição, sabedoria oculta e mistérios.',
        uprightMeaning: 'Intuição, segredos, paciência, sabedoria interior.',
        reversedMeaning: 'Segredos revelados, superficialidade, intuição ignorada.',
        suit: 'Arcanos Maiores',
        number: 2,
        keywords: ['intuição', 'mistério', 'receptividade', 'sabedoria'],
      ),
      TarotCard(
        id: '3',
        name: 'A Imperatriz',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_empress.png?alt=media&token=254ee063-25e6-4665-8cf0-ee91954da7a0',
        description: 'Fertilidade, abundância e a força da natureza.',
        uprightMeaning: 'Abundância, criatividade, natureza, nutrição.',
        reversedMeaning: 'Esterilidade, negligência, sufocamento.',
        suit: 'Arcanos Maiores',
        number: 3,
        keywords: ['criação', 'natureza', 'fertilidade', 'beleza'],
      ),
      TarotCard(
        id: '4',
        name: 'O Imperador',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_emperor.png?alt=media&token=6cab1da1-d022-4876-ab6f-20c999499334',
        description: 'Autoridade, estrutura e ordem.',
        uprightMeaning: 'Autoridade, estrutura, controle, estabilidade.',
        reversedMeaning: 'Tirania, rigidez, falta de controle.',
        suit: 'Arcanos Maiores',
        number: 4,
        keywords: ['autoridade', 'estrutura', 'ordem', 'liderança'],
      ),
      TarotCard(
        id: '5',
        name: 'O Hierofante',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_hierophant.png?alt=media&token=b4c0a8f4-da9e-4e11-9b01-c3b40db3e676',
        description: 'Tradição, espiritualidade e ensinamentos.',
        uprightMeaning: 'Tradição, espiritualidade, aprendizado, instituições.',
        reversedMeaning: 'Não conformidade, questionamento, ortodoxia.',
        suit: 'Arcanos Maiores',
        number: 5,
        keywords: ['tradição', 'sabedoria', 'ensinamento', 'moralidade'],
      ),
      TarotCard(
        id: '6',
        name: 'Os Amantes',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_lovers.png?alt=media&token=ce3d6b24-ddfa-4c5b-b8ea-1b17d3832267',
        description: 'Escolhas, relacionamentos e harmonia.',
        uprightMeaning: 'Amor, união, escolhas, harmonia.',
        reversedMeaning: 'Desarmonia, desequilíbrio, más escolhas.',
        suit: 'Arcanos Maiores',
        number: 6,
        keywords: ['amor', 'relacionamento', 'decisão', 'harmonia'],
      ),
      TarotCard(
        id: '7',
        name: 'O Carro',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_chariot.png?alt=media&token=bb0b48f3-c08e-4a82-b72a-2316cf6d2318',
        description: 'Força de vontade, direção e sucesso.',
        uprightMeaning: 'Vitória, determinação, controle, ambição.',
        reversedMeaning: 'Falta de direção, obstáculos, perda de controle.',
        suit: 'Arcanos Maiores',
        number: 7,
        keywords: ['vitória', 'ação', 'direção', 'controle'],
      ),
      TarotCard(
        id: '8',
        name: 'A Força',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_strength.png?alt=media&token=50587851-636a-4081-988c-e6308247ea86',
        description: 'Coragem, compaixão e autocontrole.',
        uprightMeaning: 'Força interior, coragem, paciência, compaixão.',
        reversedMeaning: 'Fraqueza, insegurança, raiva.',
        suit: 'Arcanos Maiores',
        number: 8,
        keywords: ['coragem', 'força', 'controle', 'compaixão'],
      ),
      TarotCard(
        id: '9',
        name: 'O Eremita',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_hermit.png?alt=media&token=e1dc32a0-3e77-45f3-88c9-6ccbb1965021',
        description: 'Introspecção, sabedoria e busca interior.',
        uprightMeaning: 'Introspecção, reflexão, solidão, sabedoria.',
        reversedMeaning: 'Solidão excessiva, isolamento, busca externa.',
        suit: 'Arcanos Maiores',
        number: 9,
        keywords: ['introspecção', 'sabedoria', 'busca', 'isolamento'],
      ),
      TarotCard(
        id: '10',
        name: 'A Roda da Fortuna',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_fortune.png?alt=media&token=11135cf0-213c-4089-9fa3-5164cc9e656f',
        description: 'Ciclos, mudança e destino.',
        uprightMeaning: 'Boa sorte, mudança, ciclos, destino.',
        reversedMeaning: 'Má sorte, resistência à mudança, eventos inesperados.',
        suit: 'Arcanos Maiores',
        number: 10,
        keywords: ['mudança', 'sorte', 'ciclos', 'destino'],
      ),
      TarotCard(
        id: '11',
        name: 'A Justiça',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_justice.png?alt=media&token=fd631106-c261-4f4a-8965-8d27d1f7021d',
        description: 'Equilíbrio, verdade e responsabilidade.',
        uprightMeaning: 'Justiça, equidade, verdade, responsabilidade.',
        reversedMeaning: 'Injustiça, desonestidade, desequilíbrio.',
        suit: 'Arcanos Maiores',
        number: 11,
        keywords: ['justiça', 'equilíbrio', 'verdade', 'responsabilidade'],
      ),
      TarotCard(
        id: '12',
        name: 'O Enforcado',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_hanged.png?alt=media&token=2ff2fc9d-74d3-47dd-bc49-942380f10266',
        description: 'Sacrifício, perspectiva e entrega.',
        uprightMeaning: 'Sacrifício, entrega, nova perspectiva, suspensão.',
        reversedMeaning: 'Estagnação, medo de sacrifício, teimosia.',
        suit: 'Arcanos Maiores',
        number: 12,
        keywords: ['sacrifício', 'perspectiva', 'entrega', 'suspensão'],
      ),
      TarotCard(
        id: '13',
        name: 'A Morte',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_death.png?alt=media&token=96415878-f5f2-4011-a4a6-14fd0c5ca6d8',
        description: 'Transformação, fim de um ciclo e novos começos.',
        uprightMeaning: 'Fim de um ciclo, transformação, renovação.',
        reversedMeaning: 'Resistência à mudança, estagnação, medo do novo.',
        suit: 'Arcanos Maiores',
        number: 13,
        keywords: ['transformação', 'fim', 'renovação', 'liberação'],
      ),
      TarotCard(
        id: '14',
        name: 'A Temperança',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_temperance.png?alt=media&token=0b84f667-0758-47d9-a446-3e77f83217c0',
        description: 'Equilíbrio, moderação e paciência.',
        uprightMeaning: 'Equilíbrio, moderação, paciência, harmonia.',
        reversedMeaning: 'Desequilíbrio, excesso, impaciência.',
        suit: 'Arcanos Maiores',
        number: 14,
        keywords: ['equilíbrio', 'moderação', 'paciência', 'harmonia'],
      ),
      TarotCard(
        id: '15',
        name: 'O Diabo',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_death.png?alt=media&token=96415878-f5f2-4011-a4a6-14fd0c5ca6d8',
        description: 'Apegos, vícios e limitações autoimpostas.',
        uprightMeaning: 'Apegos, vícios, limitações, materialismo.',
        reversedMeaning: 'Liberação, autoconsciência, superando limitações.',
        suit: 'Arcanos Maiores',
        number: 15,
        keywords: ['apego', 'limitação', 'sombra', 'materialismo'],
      ),
      TarotCard(
        id: '16',
        name: 'A Torre',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_tower.png?alt=media&token=a70bb4f3-01f7-4f3f-9402-e33302eac3c9',
        description: 'Ruptura, caos e revelação repentina.',
        uprightMeaning: 'Ruptura, caos, revelação, mudança repentina.',
        reversedMeaning: 'Resistência à mudança, evitação de desastre.',
        suit: 'Arcanos Maiores',
        number: 16,
        keywords: ['ruptura', 'caos', 'revelação', 'mudança'],
      ),
      TarotCard(
        id: '17',
        name: 'A Estrela',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_star.png?alt=media&token=8af15f74-fa6e-475c-8a1e-abd9118631ae',
        description: 'Esperança, inspiração e renovação espiritual.',
        uprightMeaning: 'Esperança, inspiração, cura, renovação.',
        reversedMeaning: 'Desespero, falta de fé, insegurança.',
        suit: 'Arcanos Maiores',
        number: 17,
        keywords: ['esperança', 'inspiração', 'cura', 'fé'],
      ),
      TarotCard(
        id: '18',
        name: 'A Lua',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_moon.png?alt=media&token=62fc145f-4d5f-49b8-8fba-5b711135be5a',
        description: 'Ilusão, medo e o inconsciente.',
        uprightMeaning: 'Intuição, sonhos, mistério, o inconsciente.',
        reversedMeaning: 'Confusão, medo, ilusão revelada.',
        suit: 'Arcanos Maiores',
        number: 18,
        keywords: ['intuição', 'medo', 'ilusão', 'inconsciente'],
      ),
      TarotCard(
        id: '19',
        name: 'O Sol',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_sun.png?alt=media&token=90eab202-4417-47d0-8a0d-0e13cf92f789',
        description: 'Alegria, vitalidade e sucesso.',
        uprightMeaning: 'Alegria, sucesso, energia, clareza.',
        reversedMeaning: 'Falta de energia, pessimismo, bloqueios.',
        suit: 'Arcanos Maiores',
        number: 19,
        keywords: ['alegria', 'sucesso', 'vitalidade', 'clareza'],
      ),
      TarotCard(
        id: '20',
        name: 'O Julgamento',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_judgement.png?alt=media&token=b018d5d5-929d-483a-be92-7f8842baec4e',
        description: 'Chamado, renascimento e avaliação.',
        uprightMeaning: 'Chamado, despertar, renascimento, avaliação.',
        reversedMeaning: 'Autocrítica, indecisão, adiamento.',
        suit: 'Arcanos Maiores',
        number: 20,
        keywords: ['chamado', 'renascimento', 'avaliação', 'perdão'],
      ),
      TarotCard(
        id: '21',
        name: 'O Mundo',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fmajor_arcana_world.png?alt=media&token=bb6b0160-8881-4fa4-95c4-86d6ea491d2f',
        description: 'Conclusão, realização e totalidade.',
        uprightMeaning: 'Conclusão, realização, integração, totalidade.',
        reversedMeaning: 'Incompletude, falta de fechamento, estagnação.',
        suit: 'Arcanos Maiores',
        number: 21,
        keywords: ['conclusão', 'realização', 'totalidade', 'harmonia'],
      ),
      // Arcanos Menores - Paus
      TarotCard(
        id: '22',
        name: 'Ás de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_ace.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Novos começos, potencial e inspiração.',
        uprightMeaning: 'Novos começos, inspiração, potencial, criatividade.',
        reversedMeaning: 'Falta de energia, indecisão, projetos abortados.',
        suit: 'Paus',
        number: 1,
        keywords: ['início', 'potencial', 'inspiração', 'energia'],
      ),
      TarotCard(
        id: '23',
        name: 'Dois de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_2.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Planejamento, decisão e parceria.',
        uprightMeaning: 'Planejamento, decisão, parceria, visão.',
        reversedMeaning: 'Falta de planejamento, indecisão, medo do desconhecido.',
        suit: 'Paus',
        number: 2,
        keywords: ['planejamento', 'decisão', 'parceria', 'oportunidade'],
      ),
      TarotCard(
        id: '24',
        name: 'Três de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_3.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Progresso, expansão e visão de futuro.',
        uprightMeaning: 'Progresso, expansão, visão de futuro, aventura.',
        reversedMeaning: 'Atrasos, falta de visão, frustração.',
        suit: 'Paus',
        number: 3,
        keywords: ['progresso', 'expansão', 'visão', 'oportunidade'],
      ),
      TarotCard(
        id: '25',
        name: 'Quatro de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_4.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Celebração, harmonia e lar.',
        uprightMeaning: 'Celebração, harmonia, lar, estabilidade.',
        reversedMeaning: 'Falta de celebração, instabilidade, conflito.',
        suit: 'Paus',
        number: 4,
        keywords: ['celebração', 'harmonia', 'lar', 'paz'],
      ),
      TarotCard(
        id: '26',
        name: 'Cinco de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_5.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Conflito, competição e desafio.',
        uprightMeaning: 'Conflito, competição, desafio, discordância.',
        reversedMeaning: 'Evitar conflito, resolução, competição desleal.',
        suit: 'Paus',
        number: 5,
        keywords: ['conflito', 'competição', 'desafio', 'discordância'],
      ),
      TarotCard(
        id: '27',
        name: 'Seis de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_6.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Vitória, reconhecimento e sucesso público.',
        uprightMeaning: 'Vitória, reconhecimento, sucesso público, confiança.',
        reversedMeaning: 'Falta de reconhecimento, egoísmo, derrota.',
        suit: 'Paus',
        number: 6,
        keywords: ['vitória', 'reconhecimento', 'sucesso', 'confiança'],
      ),
      TarotCard(
        id: '28',
        name: 'Sete de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_7.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Defesa, desafio e manter a posição.',
        uprightMeaning: 'Defesa, desafio, coragem, firmeza.',
        reversedMeaning: 'Desistir, vulnerabilidade, sobrecarga.',
        suit: 'Paus',
        number: 7,
        keywords: ['defesa', 'desafio', 'coragem', 'firmeza'],
      ),
      TarotCard(
        id: '29',
        name: 'Oito de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_8.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Movimento rápido, ação e notícias.',
        uprightMeaning: 'Movimento rápido, ação, notícias, velocidade.',
        reversedMeaning: 'Atrasos, frustração, falta de movimento.',
        suit: 'Paus',
        number: 8,
        keywords: ['movimento', 'ação', 'notícias', 'rapidez'],
      ),
      TarotCard(
        id: '30',
        name: 'Nove de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_9.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Resiliência, proteção e preparação final.',
        uprightMeaning: 'Resiliência, proteção, preparação, força interior.',
        reversedMeaning: 'Cansaço, exaustão, falta de preparação.',
        suit: 'Paus',
        number: 9,
        keywords: ['resiliência', 'proteção', 'preparação', 'força'],
      ),
      TarotCard(
        id: '31',
        name: 'Dez de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_10.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Sobrecarga, responsabilidade e fardo.',
        uprightMeaning: 'Sobrecarga, responsabilidade, fardo, exaustão.',
        reversedMeaning: 'Alívio, delegação, incapacidade de lidar.',
        suit: 'Paus',
        number: 10,
        keywords: ['sobrecarga', 'responsabilidade', 'fardo', 'peso'],
      ),
      TarotCard(
        id: '32',
        name: 'Valete de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_page.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Entusiasmo, novas ideias e mensageiro.',
        uprightMeaning: 'Entusiasmo, novas ideias, mensageiro, inspiração.',
        reversedMeaning: 'Falta de ideias, indecisão, notícias ruins.',
        suit: 'Paus',
        number: 11,
        keywords: ['entusiasmo', 'ideias', 'mensageiro', 'criatividade'],
      ),
      TarotCard(
        id: '33',
        name: 'Cavaleiro de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_knight.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Ação, aventura e impulsividade.',
        uprightMeaning: 'Ação, aventura, impulsividade, energia.',
        reversedMeaning: 'Impulsividade excessiva, imprudência, agressividade.',
        suit: 'Paus',
        number: 12,
        keywords: ['ação', 'aventura', 'impulsividade', 'energia'],
      ),
      TarotCard(
        id: '34',
        name: 'Rainha de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_queen.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Paixão, energia e independência.',
        uprightMeaning: 'Paixão, energia, independência, assertividade.',
        reversedMeaning: 'Insegurança, ciúme, agressividade passiva.',
        suit: 'Paus',
        number: 13,
        keywords: ['paixão', 'energia', 'independência', 'assertividade'],
      ),
      TarotCard(
        id: '35',
        name: 'Rei de Paus',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_wands_king.png?alt=media&token=673a8893-c80d-4bc2-9f7d-921ee63f91b3',
        description: 'Liderança, visão e autoridade.',
        uprightMeaning: 'Liderança, visão, autoridade, criatividade.',
        reversedMeaning: 'Dominância, teimosia, falta de visão.',
        suit: 'Paus',
        number: 14,
        keywords: ['liderança', 'visão', 'autoridade', 'inspiração'],
      ),
      // Arcanos Menores - Copas
      TarotCard(
        id: '36',
        name: 'Ás de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_ace.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Amor, emoção e novos relacionamentos.',
        uprightMeaning: 'Amor, emoção, novos relacionamentos, intuição.',
        reversedMeaning: 'Falta de amor, vazio emocional, oportunidades perdidas.',
        suit: 'Copas',
        number: 1,
        keywords: ['amor', 'emoção', 'relacionamento', 'intuição'],
      ),
      TarotCard(
        id: '37',
        name: 'Dois de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_2.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Parceria, união e equilíbrio emocional.',
        uprightMeaning: 'Parceria, união, amor, equilíbrio emocional.',
        reversedMeaning: 'Desarmonia, desequilíbrio, separação.',
        suit: 'Copas',
        number: 2,
        keywords: ['parceria', 'união', 'amor', 'harmonia'],
      ),
      TarotCard(
        id: '38',
        name: 'Três de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_3.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Celebração, amizade e alegria.',
        uprightMeaning: 'Celebração, amizade, alegria, comunidade.',
        reversedMeaning: 'Excesso, superficialidade, falta de apoio.',
        suit: 'Copas',
        number: 3,
        keywords: ['celebração', 'amizade', 'alegria', 'comunidade'],
      ),
      TarotCard(
        id: '39',
        name: 'Quatro de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_4.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Meditação, contemplação e oportunidades perdidas.',
        uprightMeaning: 'Meditação, contemplação, apatia, oportunidades ignoradas.',
        reversedMeaning: 'Aceitar ofertas, novas perspectivas, sair da apatia.',
        suit: 'Copas',
        number: 4,
        keywords: ['meditação', 'contemplação', 'apatia', 'reflexão'],
      ),
      TarotCard(
        id: '40',
        name: 'Cinco de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_5.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Perda, tristeza e luto.',
        uprightMeaning: 'Perda, tristeza, luto, arrependimento.',
        reversedMeaning: 'Aceitação, perdão, seguir em frente.',
        suit: 'Copas',
        number: 5,
        keywords: ['perda', 'tristeza', 'luto', 'arrependimento'],
      ),
      TarotCard(
        id: '41',
        name: 'Seis de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_6.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Nostalgia, memórias e generosidade.',
        uprightMeaning: 'Nostalgia, memórias, generosidade, compartilhar.',
        reversedMeaning: 'Prender-se ao passado, egoísmo, falta de generosidade.',
        suit: 'Copas',
        number: 6,
        keywords: ['nostalgia', 'memórias', 'generosidade', 'compartilhar'],
      ),
      TarotCard(
        id: '42',
        name: 'Sete de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_7.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Escolhas, ilusões e fantasia.',
        uprightMeaning: 'Escolhas, ilusões, fantasia, oportunidades.',
        reversedMeaning: 'Realidade, clareza, escolhas conscientes.',
        suit: 'Copas',
        number: 7,
        keywords: ['escolhas', 'ilusões', 'fantasia', 'sonhos'],
      ),
      TarotCard(
        id: '43',
        name: 'Oito de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_8.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Afastamento, abandonar o que não serve e busca interior.',
        uprightMeaning: 'Afastamento, abandonar, busca interior, deixar ir.',
        reversedMeaning: 'Medo de mudar, apego, ficar em situações ruins.',
        suit: 'Copas',
        number: 8,
        keywords: ['afastamento', 'abandono', 'busca', 'deixar_ir'],
      ),
      TarotCard(
        id: '44',
        name: 'Nove de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_9.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Realização de desejos, contentamento e bem-estar.',
        uprightMeaning: 'Realização de desejos, contentamento, bem-estar, gratidão.',
        reversedMeaning: 'Insatisfação, falta de gratidão, desejos não realizados.',
        suit: 'Copas',
        number: 9,
        keywords: ['realização', 'contentamento', 'bem-estar', 'gratidão'],
      ),
      TarotCard(
        id: '45',
        name: 'Dez de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_10.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Felicidade familiar, harmonia e plenitude emocional.',
        uprightMeaning: 'Felicidade familiar, harmonia, plenitude emocional, alegria.',
        reversedMeaning: 'Desarmonia familiar, conflitos, falta de apoio.',
        suit: 'Copas',
        number: 10,
        keywords: ['felicidade', 'harmonia', 'plenitude', 'alegria'],
      ),
      TarotCard(
        id: '46',
        name: 'Valete de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_page.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Intuição, sensibilidade e novas oportunidades emocionais.',
        uprightMeaning: 'Intuição, sensibilidade, novas oportunidades emocionais, criatividade.',
        reversedMeaning: 'Bloqueio emocional, insegurança, imaturidade.',
        suit: 'Copas',
        number: 11,
        keywords: ['intuição', 'sensibilidade', 'oportunidades', 'criatividade'],
      ),
      TarotCard(
        id: '47',
        name: 'Cavaleiro de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_knight.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Romance, charme e seguir o coração.',
        uprightMeaning: 'Romance, charme, seguir o coração, idealismo.',
        reversedMeaning: 'Instabilidade emocional, desilusão, promessas vazias.',
        suit: 'Copas',
        number: 12,
        keywords: ['romance', 'charme', 'coração', 'idealismo'],
      ),
      TarotCard(
        id: '48',
        name: 'Rainha de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_queen.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Empatia, compaixão e nutrição emocional.',
        uprightMeaning: 'Empatia, compaixão, nutrição emocional, intuição.',
        reversedMeaning: 'Instabilidade emocional, dependência, manipulação.',
        suit: 'Copas',
        number: 13,
        keywords: ['empatia', 'compaixão', 'nutrição', 'intuição'],
      ),
      TarotCard(
        id: '49',
        name: 'Rei de Copas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_cups_king.png?alt=media&token=ba9418df-48ad-4a68-ae0d-58e32dc0be0e',
        description: 'Equilíbrio emocional, diplomacia e sabedoria.',
        uprightMeaning: 'Equilíbrio emocional, diplomacia, sabedoria, compaixão.',
        reversedMeaning: 'Instabilidade emocional, manipulação, frieza.',
        suit: 'Copas',
        number: 14,
        keywords: ['equilíbrio', 'diplomacia', 'sabedoria', 'compaixão'],
      ),
      // Arcanos Menores - Espadas
      TarotCard(
        id: '50',
        name: 'Ás de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_ace.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Verdade, clareza mental e novos começos intelectuais.',
        uprightMeaning: 'Verdade, clareza mental, novos começos, intelecto.',
        reversedMeaning: 'Confusão, brutalidade, falta de clareza.',
        suit: 'Espadas',
        number: 1,
        keywords: ['verdade', 'clareza', 'intelecto', 'início'],
      ),
      TarotCard(
        id: '51',
        name: 'Dois de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_2.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Indecisão, impasse e evitar a verdade.',
        uprightMeaning: 'Indecisão, impasse, evitar a verdade, equilíbrio.',
        reversedMeaning: 'Revelação da verdade, fim do impasse, conflito.',
        suit: 'Espadas',
        number: 2,
        keywords: ['indecisão', 'impasse', 'evitar', 'equilíbrio'],
      ),
      TarotCard(
        id: '52',
        name: 'Três de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_3.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Dor, tristeza e coração partido.',
        uprightMeaning: 'Dor, tristeza, coração partido, perda.',
        reversedMeaning: 'Cura, perdão, superar a dor.',
        suit: 'Espadas',
        number: 3,
        keywords: ['dor', 'tristeza', 'perda', 'coração_partido'],
      ),
      TarotCard(
        id: '53',
        name: 'Quatro de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_4.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Descanso, recuperação e introspecção.',
        uprightMeaning: 'Descanso, recuperação, introspecção, paz.',
        reversedMeaning: 'Agitação, exaustão, evitar o descanso.',
        suit: 'Espadas',
        number: 4,
        keywords: ['descanso', 'recuperação', 'introspecção', 'paz'],
      ),
      TarotCard(
        id: '54',
        name: 'Cinco de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_5.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Conflito, derrota e desonestidade.',
        uprightMeaning: 'Conflito, derrota, desonestidade, vitória vazia.',
        reversedMeaning: 'Reconciliação, compromisso, evitar conflito.',
        suit: 'Espadas',
        number: 5,
        keywords: ['conflito', 'derrota', 'desonestidade', 'perda'],
      ),
      TarotCard(
        id: '55',
        name: 'Seis de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_6.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Transição, mudança e deixar para trás.',
        uprightMeaning: 'Transição, mudança, deixar para trás, jornada.',
        reversedMeaning: 'Resistência à mudança, ficar preso, bagagem emocional.',
        suit: 'Espadas',
        number: 6,
        keywords: ['transição', 'mudança', 'deixar_para_trás', 'jornada'],
      ),
      TarotCard(
        id: '56',
        name: 'Sete de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_7.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Engano, trapaça e furtividade.',
        uprightMeaning: 'Engano, trapaça, furtividade, esperteza.',
        reversedMeaning: 'Confissão, remorso, honestidade.',
        suit: 'Espadas',
        number: 7,
        keywords: ['engano', 'trapaça', 'furtividade', 'astúcia'],
      ),
      TarotCard(
        id: '57',
        name: 'Oito de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_8.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Restrição, aprisionamento e impotência.',
        uprightMeaning: 'Restrição, aprisionamento, impotência, vitimização.',
        reversedMeaning: 'Liberação, encontrar soluções, assumir o poder.',
        suit: 'Espadas',
        number: 8,
        keywords: ['restrição', 'aprisionamento', 'impotência', 'limitação'],
      ),
      TarotCard(
        id: '58',
        name: 'Nove de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_9.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Ansiedade, medo e culpa.',
        uprightMeaning: 'Ansiedade, medo, culpa, preocupação.',
        reversedMeaning: 'Esperança, alívio, superar a ansiedade.',
        suit: 'Espadas',
        number: 9,
        keywords: ['ansiedade', 'medo', 'culpa', 'preocupação'],
      ),
      TarotCard(
        id: '59',
        name: 'Dez de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_10.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Fim, derrota e crise.',
        uprightMeaning: 'Fim, derrota, crise, ponto final.',
        reversedMeaning: 'Recuperação, renascimento, evitar o desastre.',
        suit: 'Espadas',
        number: 10,
        keywords: ['fim', 'derrota', 'crise', 'finalização'],
      ),
      TarotCard(
        id: '60',
        name: 'Valete de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_page.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Curiosidade, comunicação e novas ideias.',
        uprightMeaning: 'Curiosidade, comunicação, novas ideias, assertividade.',
        reversedMeaning: 'Fofoca, manipulação, ideias imaturas.',
        suit: 'Espadas',
        number: 11,
        keywords: ['curiosidade', 'comunicação', 'ideias', 'assertividade'],
      ),
      TarotCard(
        id: '61',
        name: 'Cavaleiro de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_knight.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Ação, ambição e assertividade.',
        uprightMeaning: 'Ação, ambição, assertividade, determinação.',
        reversedMeaning: 'Agressividade, imprudência, falta de direção.',
        suit: 'Espadas',
        number: 12,
        keywords: ['ação', 'ambição', 'assertividade', 'determinação'],
      ),
      TarotCard(
        id: '62',
        name: 'Rainha de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_queen.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3',
        description: 'Inteligência, independência e clareza.',
        uprightMeaning: 'Inteligência, independência, clareza, objetividade.',
        reversedMeaning: 'Crueldade, sarcasmo, falta de empatia.',
        suit: 'Espadas',
        number: 13,
        keywords: ['inteligência', 'independência', 'clareza', 'objetividade'],
      ),
      TarotCard(
        id: '63',
        name: 'Rei de Espadas',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_swords_king.png?alt=media&token=97dfdaae-ae36-4d51-a724-105248defdd3?alt=media&token=fd631106-c261-4f4a-8965-8d27d1f7021d',
        description: 'Autoridade, verdade e justiça.',
        uprightMeaning: 'Autoridade, verdade, justiça, intelecto.',
        reversedMeaning: 'Tirania, injustiça, manipulação.',
        suit: 'Espadas',
        number: 14,
        keywords: ['autoridade', 'verdade', 'justiça', 'intelecto'],
      ),
      // Arcanos Menores - Ouros (Pentáculos)
      TarotCard(
        id: '64',
        name: 'Ás de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_ace.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Novas oportunidades financeiras, abundância e prosperidade.',
        uprightMeaning: 'Novas oportunidades, abundância, prosperidade, potencial.',
        reversedMeaning: 'Falta de oportunidade, ganância, investimentos ruins.',
        suit: 'Ouros',
        number: 1,
        keywords: ['oportunidade', 'abundância', 'prosperidade', 'potencial'],
      ),
      TarotCard(
        id: '65',
        name: 'Dois de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_2.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Equilíbrio, adaptação e gerenciamento de recursos.',
        uprightMeaning: 'Equilíbrio, adaptação, gerenciamento, flexibilidade.',
        reversedMeaning: 'Desequilíbrio, sobrecarga, dificuldade em adaptar.',
        suit: 'Ouros',
        number: 2,
        keywords: ['equilíbrio', 'adaptação', 'gerenciamento', 'flexibilidade'],
      ),
      TarotCard(
        id: '66',
        name: 'Três de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_3.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Colaboração, aprendizado e desenvolvimento de habilidades.',
        uprightMeaning: 'Colaboração, aprendizado, desenvolvimento, reconhecimento.',
        reversedMeaning: 'Falta de colaboração, habilidades inadequadas, preguiça.',
        suit: 'Ouros',
        number: 3,
        keywords: ['colaboração', 'aprendizado', 'desenvolvimento', 'habilidade'],
      ),
      TarotCard(
        id: '67',
        name: 'Quatro de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_4.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Estabilidade, segurança e possessividade.',
        uprightMeaning: 'Estabilidade, segurança, possessividade, controle.',
        reversedMeaning: 'Insegurança financeira, generosidade excessiva, perda.',
        suit: 'Ouros',
        number: 4,
        keywords: ['estabilidade', 'segurança', 'possessividade', 'controle'],
      ),
      TarotCard(
        id: '68',
        name: 'Cinco de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_5.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Perda financeira, dificuldades e isolamento.',
        uprightMeaning: 'Perda financeira, dificuldades, isolamento, necessidade.',
        reversedMeaning: 'Recuperação financeira, apoio, superar dificuldades.',
        suit: 'Ouros',
        number: 5,
        keywords: ['perda', 'dificuldades', 'isolamento', 'necessidade'],
      ),
      TarotCard(
        id: '69',
        name: 'Seis de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_6.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Generosidade, compartilhar e dar e receber.',
        uprightMeaning: 'Generosidade, compartilhar, dar e receber, caridade.',
        reversedMeaning: 'Egoísmo, dívida, falta de generosidade.',
        suit: 'Ouros',
        number: 6,
        keywords: ['generosidade', 'compartilhar', 'dar', 'receber'],
      ),
      TarotCard(
        id: '70',
        name: 'Sete de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_7.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Paciência, investimento a longo prazo e avaliação.',
        uprightMeaning: 'Paciência, investimento, avaliação, crescimento.',
        reversedMeaning: 'Impaciência, resultados lentos, investimentos ruins.',
        suit: 'Ouros',
        number: 7,
        keywords: ['paciência', 'investimento', 'avaliação', 'crescimento'],
      ),
      TarotCard(
        id: '71',
        name: 'Oito de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_8.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Trabalho árduo, dedicação e maestria.',
        uprightMeaning: 'Trabalho árduo, dedicação, maestria, atenção aos detalhes.',
        reversedMeaning: 'Falta de foco, trabalho de má qualidade, preguiça.',
        suit: 'Ouros',
        number: 8,
        keywords: ['trabalho', 'dedicação', 'maestria', 'detalhe'],
      ),
      TarotCard(
        id: '72',
        name: 'Nove de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_9.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Independência financeira, autossuficiência e luxo.',
        uprightMeaning: 'Independência financeira, autossuficiência, luxo, segurança.',
        reversedMeaning: 'Dependência financeira, insegurança, gastos excessivos.',
        suit: 'Ouros',
        number: 9,
        keywords: ['independência', 'autossuficiência', 'luxo', 'segurança'],
      ),
      TarotCard(
        id: '73',
        name: 'Dez de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_10.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Riqueza familiar, legado e segurança a longo prazo.',
        uprightMeaning: 'Riqueza familiar, legado, segurança a longo prazo, estabilidade.',
        reversedMeaning: 'Problemas financeiros familiares, perda de herança, risco.',
        suit: 'Ouros',
        number: 10,
        keywords: ['riqueza', 'legado', 'segurança', 'estabilidade'],
      ),
      TarotCard(
        id: '74',
        name: 'Valete de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_page.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Novas oportunidades financeiras, aprendizado prático e cautela.',
        uprightMeaning: 'Novas oportunidades financeiras, aprendizado prático, cautela, manifestação.',
        reversedMeaning: 'Má gestão financeira, falta de planejamento, oportunidades perdidas.',
        suit: 'Ouros',
        number: 11,
        keywords: ['oportunidades', 'aprendizado', 'cautela', 'manifestação'],
      ),
      TarotCard(
        id: '75',
        name: 'Cavaleiro de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_knight.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Responsabilidade, diligência e progresso constante.',
        uprightMeaning: 'Responsabilidade, diligência, progresso constante, persistência.',
        reversedMeaning: 'Preguiça, falta de foco, estagnação.',
        suit: 'Ouros',
        number: 12,
        keywords: ['responsabilidade', 'diligência', 'progresso', 'persistência'],
      ),
      TarotCard(
        id: '76',
        name: 'Rainha de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_queen.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Praticidade, nutrição e segurança material.',
        uprightMeaning: 'Praticidade, nutrição, segurança material, conforto.',
        reversedMeaning: 'Negligência, insegurança, ganância.',
        suit: 'Ouros',
        number: 13,
        keywords: ['praticidade', 'nutrição', 'segurança', 'conforto'],
      ),
      TarotCard(
        id: '77',
        name: 'Rei de Ouros',
        imageUrl: 'https://firebasestorage.googleapis.com/v0/b/oraculum-app-dcde3.firebasestorage.app/o/cards%2Fminor_arcana_pentacles_king.png?alt=media&token=5607832f-5f47-4558-94ff-550d30ecb668',
        description: 'Abundância, sucesso material e liderança prática.',
        uprightMeaning: 'Abundância, sucesso material, liderança prática, estabilidade.',
        reversedMeaning: 'Ganância, teimosia, falta de visão.',
        suit: 'Ouros',
        number: 14,
        keywords: ['abundância', 'sucesso', 'liderança', 'estabilidade'],
      ),
    ];
  }

}