// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3cZd7uPj_9GKstUJvCoRqarcYQcSSMC0',
    appId: '1:558056975643:android:1d4a5853618faa370937be',
    messagingSenderId: '558056975643',
    projectId: 'oraculum-app-dcde3',
    storageBucket: 'oraculum-app-dcde3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVdEl5vlTS3CDtr-BAjU7CkAzesM3hqIY',
    appId: '1:558056975643:ios:35a11af1a6b5e2370937be',
    messagingSenderId: '558056975643',
    projectId: 'oraculum-app-dcde3',
    storageBucket: 'oraculum-app-dcde3.firebasestorage.app',
    androidClientId: '558056975643-lem38nve503188e0kgdnecca756vmjlp.apps.googleusercontent.com',
    iosClientId: '558056975643-pfmb1t0ita25kfc49a5hmnvs71hbf6g7.apps.googleusercontent.com',
    iosBundleId: 'com.selddon.oraculum',
  );

}